### ISSUE TITLE
devDependencies to old

### ISSUE THREAD

**Issue by tecio-first** [AlbericoD/overwolf-modern-react-boilerplate#181]
**Describe the bug**
A fresh install of this template will trow a Error in the End related to SQLITE.
NPX or Yarn does not matter.

Kicking out of --> "remotedev-server": "^0.3.1", get you at least the NPM Install done.
Alternativ: --> "@redux-devtools/cli": "^4.0.0", ?

`    "scripts": {
      "start-remote-server": "redux-devtools --hostname=localhost --port=8000",`

https://github.com/zalmoxisus/remotedev-server/commit/ce866a8bb8a5b49943f70acbc895ee8a8c6455ee

>This package was renamed to [`redux-devtools-cli`](https://github.com/reduxjs/redux-devtools/tree/master/packages/redux-devtools-cli) and merged into [`redux-devtools` monorepo](https://github.com/reduxjs/redux-devtools). Please refer to that repository for the latest updates, issues and pull requests.

second thing: 

"@overwolf/types": "^3.24.6", has also an update ;-)

KR
[Uploading 2024-01-05T12_59_23_829Z-debug-0.log…]()

LOG for Information was added

After this change errors are gone:

`
tecio@Framework:~/playground/overwolf-modern-react-boilerplate$ npx create-react-app my-app3 --template file:.

Creating a new React app in /home/tecio/playground/overwolf-modern-react-boilerplate/my-app3.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template-overwolf-typescript-redux...

added 1484 packages in 1m

250 packages are looking for funding
  run `npm fund` for details

Installing template dependencies using npm...
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated redux-devtools-instrument@1.10.0: Package moved to @redux-devtools/instrument.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated remotedev-serialize@0.1.9: Package moved to @redux-devtools/serialize.
npm WARN deprecated redux-devtools-core@0.2.1: Package moved to @redux-devtools/app.
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 566 packages, and changed 2 packages in 1m

288 packages are looking for funding
  run `npm fund` for details

The following changes are being made to your tsconfig.json file:
  - compilerOptions.jsx must be react-jsx (to support the new JSX transform in React 17)

Removing template package using npm...

removed 1 package, and audited 2051 packages in 2s

288 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

Success! Created my-app3 at /home/tecio/playground/overwolf-modern-react-boilerplate/my-app3
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd my-app3
  npm start

Happy hacking!
tecio@Framework:~/playground/overwolf-modern-react-boilerplate$

`

**Comment by AlbericoD** [comment]
hi, thanks for the report, I'm working on the new version with the updated packages
