### ISSUE TITLE
npm run pack-overwolf failed to create a Files folder.

### ISSUE THREAD

**Issue by artem-alek** [AlbericoD/overwolf-modern-react-boilerplate#4]
**Describe the bug**
`create-production-overwolf-build.sh` failed to create a Files folder in app folder. Which fails to correctly package the app bundle to zip and install opk package to overwolf client.

**Before:**
`cd app
mv ../index.html Files
mv ../static Files
echo 'Compiled successfully!'`

**After**
`cd app
mkdir Files
mv ../index.html Files
mv ../static Files
echo 'Compiled successfully!'`

Alternatively, you can add `Files` folder to the public/app and will be built with npm run build.

**Comment by AlbericoD** [comment]
I think we can close, we received help for this problem
